fruits = ["apple","banana","cherry"]
print("original list:",fruits)
print("first fruit:",fruits[0])
print("last fruit:", fruits[-1])
fruits.append("orange")
print("after appending:",fruits)
fruits.insert(1,"mango")
print("after inserting at position 1:",fruits)
fruits.remove("banana")
print("after removing 'banana':",fruits)
fruits.sort()
print("after sorting:",fruits)
fruits.reverse()
print("after reversing:",fruits)
print("number of fruits:",len(fruits))
