colors = ("red","green","blue")
print("original tuple:",colors)
print("first color:",colors[0])
print("last color:",colors[-1])
print("first two colors:",colors[:2])
print("is'green' in the tuple?","green" in colors)
print("number of colors:",len(colors))
nested = (1,2,("a","b"))
print("nested tuple:",nested)
print("element from nested tuple:",nested[2][1])
new_colors = colors+("yellow","purple")
print("concatenated tuple:", new_colors)
repeat = ("hi",)*3
print("repeated tuple:", repeat)
